### ISSUE TITLE
Compute the cost of chat completion tasks 

### ISSUE THREAD

**Issue by Mohannadcse** [langroid/langroid#216]
**Describe the solution you'd like**
Reporting cost + the total number of tokens + potentially saving for chat completion tasks. 
Currently, OpenAI doesn't report these aspects like the completion API.

**Additional context**
The main logic is as follows:
1. Compute the total tokens for each LLM response
1.1. Leverage the attribute `usage` under the class `ChatDocMetaData`. Set this attribute `response.metadata.usage = self.num_tokens(response.content) + self.chat_num_tokens(hist)`
1.2. Add `usage` attribute under the class `LLMMessage`. Then, for every [LLM response](https://github.com/langroid/langroid/blob/main/langroid/agent/chat_agent.py#L404),  set this attribute.
1.3. make sure to set the usage attribute when the response is converted to [`LLMMessage`](https://github.com/langroid/langroid/blob/main/langroid/agent/chat_document.py#L156)
2. Aggregate the total tokens for ALL LLM responses
2.1. iterate over the list `message_history` and get the value of the `usage` attribute, and sum them up. _Should I exclude cached responses??_
2.2. I may need to add an attribute `total_tokens` to the class `ChatAgent` to report the total number of tokens 
3. Compute the cost

**Comment by Mohannadcse** [comment]
@pchalasani what do you think about this logic?

**Comment by Mohannadcse** [comment]
I can't add `usage` to [LLMMessage](https://github.com/langroid/langroid/blob/main/langroid/agent/chat_document.py#L156)

**Comment by pchalasani** [comment]
Token cost is incurred every time we get an LLM response. I think the right place to track & accumulate token cost is inside the `ChatAgent`. When `ChatAgent.llm_response_messages` is invoked with a list of messages $m_1, m_2, ... m_k$, and a response $r$ is obtained, total token cost incurred is:
- if $r$ is a cached response, then 0
- otherwise, it is roughly $T(m_1) + T(m_2) + ... T(m_k) + T(r)$, where $T(.)$ is the `num_tokens` fn

`LLMResponse` does have a `usage` field, but it is not populated in some scenarios, e.g. streaming. I think extracting `usage` info in streaming mode is not straightforward. Maybe check the OpenAI forums and OpenAI cookbooks on cost/usage computation in various scenarios.

**Comment by Mohannadcse** [comment]
This is what I did, but I had to create a List that will maintain all responses (similar to message_history) to compute total tokens. 
But for streaming, don't we have access to the `content` field in the `ChatDocument`? so after receiving the response, we can do something like this to count number of tokens in the `content` field:
```
with StreamingIfAllowed(self.llm):
            response = self.llm_response_messages(hist, output_len)
            response.metadata.usage = self.num_tokens(
                response.content
            ) + self.chat_num_tokens(hist)
```

**Comment by pchalasani** [comment]
Agreed. Output cost is double the Input cost so it’s not a trivial diff

**Comment by Mohannadcse** [comment]
So I'm working now on changing `usage` field in the class `LLMResponse` to a Dict, then we can easily compute the cost

**Comment by Mohannadcse** [comment]
solved on this PR https://github.com/langroid/langroid/pull/227
