### ISSUE TITLE
unstructured.io integration request

### ISSUE THREAD

**Issue by ranjancse26** [langroid/langroid#277]
**Is your feature request related to a problem? Please describe.**
Integrate with https://unstructured.io/ for handling various document types.

**Describe the solution you'd like**
It would be nice to see the unstructured integration for handling a ton of known document types or formats.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by pchalasani** [comment]
Langroid has unstructured.io as one of the options for pdfs, and as the only option for docx files.
However it's currently not the default for pdfs since there were some stability issues with their lib. 
See our integration here -

https://github.com/langroid/langroid/blob/main/langroid/parsing/document_parser.py
