### ISSUE TITLE
Update to Pydantic 2.0

### ISSUE THREAD

**Issue by pchalasani** [langroid/langroid#358]
At some point :)

**Comment by sanders41** [comment]
For now you are blocked on this by agent-search. The latest version `0.0.9` still depends on pydantic < 2

```console
Because agent-search (0.0.9) depends on pydantic (>=1.10.13,<2.0.0)
 and no versions of agent-search match >0.0.9,<0.0.10, agent-search (>=0.0.9,<0.0.10) requires pydantic (>=1.10.13,<2.0.0).
So, because langroid depends on both pydantic (2.5.3) and agent-search (^0.0.9), version solving failed.
```

**Comment by pchalasani** [comment]
> blocked on this by agent-search.

I'm surprised this is the only blocker (if so, that's a minor one, since agent-search is just an extra and we can work around that)... I was expecting a lot of similar conflicts.

**Comment by sanders41** [comment]
I haven't run into a situation where I had multiple conflicts before so I'm not sure how the Poetry resolver handles this. It's quite possible that it hit the first conflict and quit without reporting the others. So removing agent-search may bring out other conflicts.

**Comment by Mohannadcse** [comment]
Not sure if this is helpful, but here is a glance about langroid dependency on pydantic:
It mainly relies on pydantic version `1.10.13`. Here are the multiple paths between "langroid" and "pydantic" version "1.10.13". 
1. `langroid` -> `chromadb` -> `fastapi` -> `pydantic` version "1.10.13"
2. `langroid` -> `chromadb` -> `pydantic` version "1.10.13"
3. `langroid` -> `farm-haystack` -> `pydantic` version "1.10.13"
4. `langroid` -> `farm-haystack` -> `quantulum3` -> `inflect` -> `pydantic` version "1.10.13"
5. `langroid` -> `lancedb` -> `pydantic` version "1.10.13"
6. `langroid` -> `meilisearch` -> `camel-converter` -> `pydantic` version "1.10.13"
7. `langroid` -> `meilisearch-python-sdk` -> `camel-converter` -> `pydantic` version "1.10.13"
8. `langroid` -> `meilisearch-python-sdk` -> `pydantic` version "1.10.13"
9. `langroid` -> `openai` -> `pydantic` version "1.10.13"
11. `langroid` -> `pydantic` version "1.10.13"
12. `langroid` -> `qdrant-client` -> `pydantic` version "1.10.13"

<img width="911" alt="image" src="https://github.com/langroid/langroid/assets/15859139/5a849345-3bb6-46b3-8ba8-cd26bd2fb61c">


However, there is this transitive dependency, where some langroid dependencies use pyndantic version 2.5.3. That's why in the picture below it shows this package isn't imported (the node doesn't have the imported attribute). Here are multiple paths between "langroid" and "pydantic" version "2.5.3". 

1. `langroid` -> `chromadb` -> `fastapi` -> `pydantic` version "2.5.3"
2. `langroid` -> `chromadb` -> `pydantic` version "2.5.3"
3. `langroid` -> `farm-haystack` -> `quantulum3` -> `inflect` -> `pydantic` version "2.5.3"
4. `langroid` -> `lancedb` -> `pydantic` version "2.5.3"
5. `langroid` -> `meilisearch` -> `camel-converter` -> `pydantic` version "2.5.3"
6. `langroid` -> `meilisearch-python-sdk` -> `camel-converter` -> `pydantic` version "2.5.3"
7. `langroid` -> `meilisearch-python-sdk` -> `pydantic` version "2.5.3"
8. `langroid` -> `openai` -> `pydantic` version "2.5.3"
9. `langroid` -> `qdrant-client` -> `pydantic` version "2.5.3"

<img width="907" alt="image" src="https://github.com/langroid/langroid/assets/15859139/4f072799-c0d9-4db7-a75a-2e4349c618e4">

**Comment by sanders41** [comment]
On a quick scan through requirements files it looks like all the other dependencies have `pydantic >= 1.x` so they allow 2+ also. 

I happen to be the maintainer of camel-converter and meilisearch-python-sdk, and one of the meilisearch client maintainers so I now for sure that is the case on those :smile:

**Comment by pchalasani** [comment]
@sanders41 finally got this done in PR #498  -- langroid now works with Pydantic v1 or v2

**Comment by sanders41** [comment]
Thanks for the heads up @pchalasani. Do you know how long you plan to support Pydantic v1? My current tentative plan in my libraries is to drop support for it with a release in Oct/Nov when Python 3.8 goes EOL and doing a release for that. Will this cause issues for you, or could you pin to versions < the new major version? If it will cause issues I could continue to support it for a while longer.

As a side note, I noticed you are using both the `meilisearch-python-sdk` and the `meilisearch` libraries. You could drop one of those and have one less dependency to install. Since you are using the `AsyncClient` from `meilisearch-python-sdk` it would make sense to keep that one. If you want me to do a PR to remove the other let me know and I can.

**Comment by pchalasani** [comment]
@sanders41 

> Will this cause issues for you, or could you pin to versions < the new major version? If it will cause issues I could continue to support it for a while longer.

Installing langroid by default installs pydantic 2.x, so discontinuing meilisearch v1 support shouldn't be an issue.



> If you want me to do a PR to remove the other let me know and I can.

That would be great, thanks.
