### ISSUE TITLE
custom behavior for InfiniteLoopException

### ISSUE THREAD

**Issue by isspek** [langroid/langroid#644]
Thanks for the great library!

We have a question related to the InfiniteLoopException. In our use case, two LLM agents make discussions, after some time a discussion can lead a result through a ResultTool. In our setup, interactive is False, because we don't use an user input. We noted that we receive sometimes InfiniteLoopException, especially when one of LLM does not return a response. We would like to overwrite this behavior if we get InfiniteLoopException. How can we achieve this? Which object is responsible for that: ChatAgent, agent.ToolMessage.

Thanks in advance.
Ipek

**Comment by pchalasani** [comment]
Glad you like it! 

To completely turn off inf loop detection, you can create a config

```
task_config = TaskConfig(inf_loop_cycle_len=0)
```
and use this config when you set up a task, e.g. `task = Task(..., config=task_config)`

But maybe you're asking about how to override the behavior of an agent when the LLM does not return a response  -- I'm not sure how this happens, since the `llm_response` method _always_ returns some response (i.e. LLM doesn't simple respond with an empty string). 

I made a simple 2-agent discussion example [here](https://github.com/langroid/langroid/blob/main/examples/basic/chat-2-agent-discuss.py).

Or did you mean you want to handle a scenario where the LLM doesn't return a tool?

**Comment by isspek** [comment]
Thanks for your example. Much appreciated! As you indicated in your last sentence, we actually want to handle a scenario where the LLM doesn't return a tool. We use handle methods, but we still get infinite loop error.

**Comment by pchalasani** [comment]
So to be clear, your scenario is where the "sub-agent" is expected to return a tool but doesn't, and so it loops forever? Ideally I'd like to look at a minimal code snippet, but the main remedy for this type of situation is to define a `handle_message_fallback` method on your `ChatAgent`. This method gets invoked when the Agent's `agent_response` method (which normally handles tools) does _not_ see a tool. By default this method does nothing, but it is meant to be overriden if needed. There is an FAQ about this [here](https://langroid.github.io/langroid/FAQ/#how-can-i-handle-an-llm-forgetting-to-generate-a-toolmessage).

See the example [`2-agent-tool.py`](https://github.com/langroid/langroid/blob/main/examples/basic/2-agent-tools.py) and numerous other examples, see image.

<img width="878" alt="image" src="https://github.com/user-attachments/assets/d658d327-86a3-4f8e-8909-f7b0e31f4edb" />

**Comment by pchalasani** [comment]
Is `Agentx` the "parent" agent? In that case, 
- in `handle` method, istead of `SendTool`,  use `AgentDoneTool(content=self.answer)`
- in the fallback method, instead of `ForwardTool`, use `AgentDoneTool(content=msg.content)`

This is my best guess without knowing your full script.

**Comment by isspek** [comment]
Yes, Agentx is a parent agent. Thanks for the recommendations. We will apply them to our configuration. I am closing the issue.
